name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Format check and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1.2.0-M3
        with:
          jvm: temurin:1.17
          apps: scala-cli scalafmt

      - name: Format check
        run: scalafmt --check src/ test/

      - name: Test
        run: scala-cli test .
